/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cosaschachis;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author silvia
 */
public class NewJFrameTable extends javax.swing.JFrame {

    ArrayList<Alumno> listaAlumnos;
    JTable jTableAlumnos;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrameTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameTable().setVisible(true);
            }
        });
    }
    
    public void jButtonActionPerformedMensaje(java.awt.event.ActionEvent evt){
        JOptionPane.showMessageDialog(this, "Este es el mensaje", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void jButtonActionPerformedConfirmacion(java.awt.event.ActionEvent evt){
        int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres realizar la accion?", "Confirmacion", JOptionPane.QUESTION_MESSAGE);
        if (resultado == JOptionPane.YES_OPTION){
            // Si dice que si
        }else if (resultado == JOptionPane.NO_OPTION){
            // Si dice que no
        }else{
            // Si cierra la ventana
        }
    }
    
    private void rellenarTablaDefaultModel(){
        String[] columnas = {"Nombre","Curso"};
        // Este modelo por defecto solo sabe mostrar strings
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        for(Alumno alumno : listaAlumnos){
            String[] datos = {alumno.getNombre(),alumno.getCurso()};
            dtm.addRow(datos);
        }
        jTableAlumnos.setModel(dtm);
    }
    
    private void rellenarTablaAlumnoModel(){
        TableModelAlumnos tma = new TableModelAlumnos(listaAlumnos);
        jTableAlumnos.setModel(tma);
    }

    public class TableModelAlumnos extends AbstractTableModel{

        private final ArrayList listaAlumnos;
        private final String[] columnas = {"Nombre", "Curso"};

        public TableModelAlumnos(ArrayList listaAlumnos) {
            this.listaAlumnos = listaAlumnos;
        }
        
        @Override
        public int getRowCount() {
            return listaAlumnos.size();
        }

        @Override
        public int getColumnCount() {
            return columnas.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            //return (columnIndex == 0)?(listaAlumnos.get(rowIndex).getNombre()):(listaAlumnos.get(rowIndex).getCurso());
            return null;
        }
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
