/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dto.Carrera;
import dto.Corredor;
import dto.TiemposCorredor;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logicaNegocio.Logica;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author silvia
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Logica logica;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.logica = new Logica();
        inicializarButtonGroup();
        inicializarComboBox();
    }

    private void inicializarButtonGroup() {
        this.buttonGroup.add(this.jRadioButtonCarrerasSinFinalizar);
        this.buttonGroup.add(this.jRadioButtonCarrera);
        this.buttonGroup.add(this.jRadioButtonCarreraFinalizada);
        this.buttonGroup.add(this.jRadioButtonCorredor);
        this.buttonGroup.setSelected(this.jRadioButtonCarrerasSinFinalizar.getModel(), true);
    }

    private void inicializarComboBox() {
        for (Carrera c : logica.getCarreras()) {
            this.jComboBoxIdCarrera.addItem(c.getId());
        }
        this.jComboBoxIdCarrera.setSelectedIndex(0);

        for (Carrera c : logica.getCarrerasFinalizadas()) {
            this.jComboBoxIdCarreraFinalizada.addItem(c.getId());
        }
        this.jComboBoxIdCarreraFinalizada.setSelectedIndex(0);

        for (Corredor c : logica.getCorredores()) {
            this.jComboBoxDniCorredor.addItem(c.getDni());
        }
        this.jComboBoxIdCarreraFinalizada.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelRadioButtons = new javax.swing.JPanel();
        jRadioButtonCarrerasSinFinalizar = new javax.swing.JRadioButton();
        jRadioButtonCarrera = new javax.swing.JRadioButton();
        jRadioButtonCarreraFinalizada = new javax.swing.JRadioButton();
        jRadioButtonCorredor = new javax.swing.JRadioButton();
        jComboBoxIdCarrera = new javax.swing.JComboBox<>();
        jLabelIdCarreraFinalizada = new javax.swing.JLabel();
        jLabelIdCarrera = new javax.swing.JLabel();
        jComboBoxIdCarreraFinalizada = new javax.swing.JComboBox<>();
        jLabelDniCorredor = new javax.swing.JLabel();
        jComboBoxDniCorredor = new javax.swing.JComboBox<>();
        jButtonGenerarInforme = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInformeExamen2Eval = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelTitulo.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("INFORMES GESTIÓN CARRERAS");

        jRadioButtonCarrerasSinFinalizar.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jRadioButtonCarrerasSinFinalizar.setText("Carreras sin finalizar");

        jRadioButtonCarrera.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jRadioButtonCarrera.setText("Carrera");

        jRadioButtonCarreraFinalizada.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jRadioButtonCarreraFinalizada.setText("Carrera finalizada");

        jRadioButtonCorredor.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jRadioButtonCorredor.setText("Corredor");

        jComboBoxIdCarrera.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N

        jLabelIdCarreraFinalizada.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N
        jLabelIdCarreraFinalizada.setText("Id ");

        jLabelIdCarrera.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N
        jLabelIdCarrera.setText("Id ");

        jComboBoxIdCarreraFinalizada.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N

        jLabelDniCorredor.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N
        jLabelDniCorredor.setText("Dni");

        jComboBoxDniCorredor.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanelRadioButtonsLayout = new javax.swing.GroupLayout(jPanelRadioButtons);
        jPanelRadioButtons.setLayout(jPanelRadioButtonsLayout);
        jPanelRadioButtonsLayout.setHorizontalGroup(
            jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRadioButtonsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRadioButtonsLayout.createSequentialGroup()
                        .addComponent(jRadioButtonCarrerasSinFinalizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRadioButtonsLayout.createSequentialGroup()
                        .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadioButtonCarreraFinalizada, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jRadioButtonCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdCarreraFinalizada)
                            .addComponent(jLabelIdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDniCorredor))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxIdCarreraFinalizada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDniCorredor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxIdCarrera, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );
        jPanelRadioButtonsLayout.setVerticalGroup(
            jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRadioButtonsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jRadioButtonCarrerasSinFinalizar)
                .addGap(18, 18, 18)
                .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCarrera)
                    .addComponent(jComboBoxIdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCarreraFinalizada)
                    .addComponent(jLabelIdCarreraFinalizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxIdCarreraFinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCorredor)
                    .addComponent(jLabelDniCorredor)
                    .addComponent(jComboBoxDniCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jButtonGenerarInforme.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jButtonGenerarInforme.setText("GENERAR INFORME");
        jButtonGenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButtonGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRadioButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRadioButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jMenu1.setText("Informes");

        jMenuItemInformeExamen2Eval.setText("InformeExamen2Eval");
        jMenuItemInformeExamen2Eval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformeExamen2EvalActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemInformeExamen2Eval);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarInformeActionPerformed

        Map parametros = new HashMap();
        String ruta = pedirRutaInforme();

        if (ruta != null) {
            ruta += ".pdf";

            try {

                if (this.jRadioButtonCarrerasSinFinalizar.isSelected()) {

                    ArrayList<Carrera> carrerasSinFinalizar = logica.getCarrerasSinFinalizar();
                    JRDataSource dataSource = new JRBeanCollectionDataSource(carrerasSinFinalizar);
                    JasperPrint print = JasperFillManager.fillReport("informes"+File.separator+"InformeCarrerasSinFinalizar.jasper", parametros, dataSource);
                    JasperExportManager.exportReportToPdfFile(print, ruta);

                } else if (this.jRadioButtonCarrera.isSelected()) {

                    Carrera carreraElegida = logica.getCarrera(this.jComboBoxIdCarrera.getSelectedItem().toString());
                    System.out.println(this.jComboBoxIdCarrera.getSelectedItem().toString());
                    parametros.put("ID", carreraElegida.getId());
                    parametros.put("ESTADO", carreraElegida.getEstadoCarrera());

                    JRDataSource dataSource = new JRBeanCollectionDataSource(carreraElegida.getListaCorredores());
                    JasperPrint print = JasperFillManager.fillReport("informes"+File.separator+"CarreraElegida.jasper", parametros, dataSource);
                    JasperExportManager.exportReportToPdfFile(print, ruta);

                } else if (this.jRadioButtonCarreraFinalizada.isSelected()) {

                    Carrera carreraElegida = logica.getCarrera(this.jComboBoxIdCarreraFinalizada.getSelectedItem().toString());
                    parametros.put("ID", carreraElegida.getId());
                    parametros.put("NOMBRE", carreraElegida.getNombre());
                    parametros.put("FECHA", carreraElegida.getFecha());

                    JRDataSource dataSource = new JRBeanCollectionDataSource(carreraElegida.getListaClasificacionCorredores());
                    JasperPrint print = JasperFillManager.fillReport("informes"+File.separator+"CarreraElegidaFinalizada.jasper", parametros, dataSource);
                    JasperExportManager.exportReportToPdfFile(print, ruta);

                } else if (this.jRadioButtonCorredor.isSelected()) {

                    Corredor corredorElegido = logica.getCorredor(this.jComboBoxDniCorredor.getSelectedItem().toString());
                    parametros.put("DNI", corredorElegido.getDni());
                    parametros.put("NOMBRE", corredorElegido.getNombre());
                    parametros.put("FECHA", corredorElegido.getFecha_nac());
                    parametros.put("DIR", corredorElegido.getDireccion());
                    parametros.put("TEL", corredorElegido.getTelefono());

                    ArrayList<Carrera> carrerasCorredor = logica.getCarrerasCorredor(corredorElegido.getDni());
                    if (carrerasCorredor == null) {
                        // Añado una carrera vacia porque si no el informe sale en blanco
                        carrerasCorredor = new ArrayList();
                        carrerasCorredor.add(new Carrera("", "", new Date(), "", 0));
                        JRDataSource dataSource = new JRBeanCollectionDataSource(carrerasCorredor);
                        JasperPrint print = JasperFillManager.fillReport("informes"+File.separator+"CorredorElegidoSinCarreras.jasper", parametros, dataSource);
                        JasperExportManager.exportReportToPdfFile(print, ruta);
                    } else {
                        JRDataSource dataSource = new JRBeanCollectionDataSource(carrerasCorredor);
                        JasperPrint print = JasperFillManager.fillReport("informes"+File.separator+"CorredorElegido.jasper", parametros, dataSource);
                        JasperExportManager.exportReportToPdfFile(print, ruta);
                    }

                }

                JOptionPane.showMessageDialog(this, "El informe se ha generado correctamente", "Informe generado", JOptionPane.INFORMATION_MESSAGE);
                // No es compatible con mi sistema
                // Desktop.getDesktop().open(ruta);

            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido problemas en la generacion del informe", "Problemas con el informe", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonGenerarInformeActionPerformed

    private void jMenuItemInformeExamen2EvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformeExamen2EvalActionPerformed
        Map parametros = new HashMap();
        String ruta = pedirRutaInforme();

        if (ruta != null) {
            try {
                ruta += ".pdf";
                
                ArrayList<TiemposCorredor> corredoresApuntadosCarreras = logica.getCorredoresApuntadosCarreras();
                // Ordeno la coleccion por dni para agrupar en el informe
                Collections.sort(corredoresApuntadosCarreras, new Comparator<TiemposCorredor>() {
                    @Override
                    public int compare(TiemposCorredor o1, TiemposCorredor o2) {
                        return o1.getDni().compareToIgnoreCase(o2.getDni());
                    }
                });
                
                JRDataSource dataSource = new JRBeanCollectionDataSource(corredoresApuntadosCarreras);
                JasperPrint print = JasperFillManager.fillReport("informes"+File.separator+"InformeExamen2Eval.jasper", parametros, dataSource);
                JasperExportManager.exportReportToPdfFile(print, ruta);
                
                JOptionPane.showMessageDialog(this, "El informe se ha generado correctamente", "Informe generado", JOptionPane.INFORMATION_MESSAGE);
               
                
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido problemas en la generacion del informe", "Problemas con el informe", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_jMenuItemInformeExamen2EvalActionPerformed

    private String pedirRutaInforme() {
        JFileChooser jfc = new JFileChooser();
        int resultado = jfc.showSaveDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            return jfc.getSelectedFile().getAbsolutePath();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha indicado donde guardar el archivo por lo tanto no se generará el informe.", "Sin ruta especificada", JOptionPane.INFORMATION_MESSAGE);
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonGenerarInforme;
    private javax.swing.JComboBox<String> jComboBoxDniCorredor;
    private javax.swing.JComboBox<String> jComboBoxIdCarrera;
    private javax.swing.JComboBox<String> jComboBoxIdCarreraFinalizada;
    private javax.swing.JLabel jLabelDniCorredor;
    private javax.swing.JLabel jLabelIdCarrera;
    private javax.swing.JLabel jLabelIdCarreraFinalizada;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInformeExamen2Eval;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRadioButtons;
    private javax.swing.JRadioButton jRadioButtonCarrera;
    private javax.swing.JRadioButton jRadioButtonCarreraFinalizada;
    private javax.swing.JRadioButton jRadioButtonCarrerasSinFinalizar;
    private javax.swing.JRadioButton jRadioButtonCorredor;
    // End of variables declaration//GEN-END:variables
}
