package gui;

import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import logic.LogicaGuardado;
import utils.Utiles;

/**
 *
 * @author silvia
 */
public class DialogoOpciones extends javax.swing.JDialog {
    
    private int frecuenciaGuardado;


    /**
     * Creates new form FormularioCorredor
     *
     * @param parent
     * @param modal
     */
    public DialogoOpciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        jSliderFrecuenciaGuardado.setPaintLabels(true);
        jSliderFrecuenciaGuardado.setLabelTable(jSliderFrecuenciaGuardado.createStandardLabels(5));
        jSliderFrecuenciaGuardado.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                frecuenciaGuardado = jSliderFrecuenciaGuardado.getValue();
                jLabelValorFrecuencia.setText(String.valueOf(frecuenciaGuardado));}
        });
        frecuenciaGuardado = LogicaGuardado.getInstance()
                .getConfiguracion().getIntervaloDeGuardado();
        jSliderFrecuenciaGuardado.setValue(frecuenciaGuardado);
        jLabelValorFrecuencia.setText(String.valueOf(frecuenciaGuardado));
    }

                
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotones = new javax.swing.JPanel();
        jButtonGuardarOpciones = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jLabelTextoFrecuenciaGuardado = new javax.swing.JLabel();
        jSliderFrecuenciaGuardado = new javax.swing.JSlider();
        jLabelValorFrecuencia = new javax.swing.JLabel();
        jLabelTextoMinutos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones");
        setForeground(java.awt.Color.darkGray);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(480, 200));
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        jPanelBotones.setMaximumSize(new java.awt.Dimension(480, 100));
        jPanelBotones.setMinimumSize(new java.awt.Dimension(480, 70));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(480, 70));

        jButtonGuardarOpciones.setFont(new java.awt.Font("Uroob", 1, 24)); // NOI18N
        jButtonGuardarOpciones.setText("GUARDAR");
        jButtonGuardarOpciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardarOpciones.setMinimumSize(new java.awt.Dimension(85, 40));
        jButtonGuardarOpciones.setPreferredSize(new java.awt.Dimension(85, 40));
        jButtonGuardarOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarOpcionesActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Uroob", 1, 24)); // NOI18N
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(85, 40));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(85, 40));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButtonGuardarOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanelBotonesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonGuardarOpciones});

        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanelBotones, java.awt.BorderLayout.PAGE_END);

        jPanel.setMaximumSize(null);
        jPanel.setMinimumSize(new java.awt.Dimension(480, 170));
        jPanel.setPreferredSize(new java.awt.Dimension(480, 170));

        jLabelTextoFrecuenciaGuardado.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabelTextoFrecuenciaGuardado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoFrecuenciaGuardado.setText("Frecuencia de guardado");
        jLabelTextoFrecuenciaGuardado.setMinimumSize(new java.awt.Dimension(40, 12));
        jLabelTextoFrecuenciaGuardado.setPreferredSize(new java.awt.Dimension(40, 12));

        jSliderFrecuenciaGuardado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSliderFrecuenciaGuardado.setMaximum(60);
        jSliderFrecuenciaGuardado.setMinimum(5);
        jSliderFrecuenciaGuardado.setPaintLabels(true);
        jSliderFrecuenciaGuardado.setValue(30);

        jLabelValorFrecuencia.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabelValorFrecuencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValorFrecuencia.setText("30");

        jLabelTextoMinutos.setFont(new java.awt.Font("Uroob", 1, 24)); // NOI18N
        jLabelTextoMinutos.setText("MINUTOS");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTextoFrecuenciaGuardado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jSliderFrecuenciaGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelValorFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTextoMinutos)
                .addGap(166, 166, 166))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTextoFrecuenciaGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSliderFrecuenciaGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValorFrecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextoMinutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);
        jPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Utiles.salirSinGuardar(this);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarOpcionesActionPerformed
      LogicaGuardado.getInstance().setIntervaloGuardado(frecuenciaGuardado);
      dispose();
    }//GEN-LAST:event_jButtonGuardarOpcionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardarOpciones;
    private javax.swing.JLabel jLabelTextoFrecuenciaGuardado;
    private javax.swing.JLabel jLabelTextoMinutos;
    private javax.swing.JLabel jLabelValorFrecuencia;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JSlider jSliderFrecuenciaGuardado;
    // End of variables declaration//GEN-END:variables
}
