package interfaz;

import logica.LogicaCorredor;
import java.io.IOException;

/**
 *
 * @author silvia
 */
public class JDialogVerCorredores extends javax.swing.JDialog {

    /**
     * Creates new form PantallaCorredor
     *
     * @param parent
     * @param modal
     */
    public JDialogVerCorredores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            this.jListCorredores.set;
            this.setVisible(true);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTituloVerCorredores = new javax.swing.JPanel();
        jLabelTituloVerCorredores = new javax.swing.JLabel();
        jPanelListaCorredores = new javax.swing.JPanel();
        jScrollCorredores = new javax.swing.JScrollPane();
        jListCorredores = new javax.swing.JList<>();
        jPanelBotonesListaCorredores = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));

        jPanelTituloVerCorredores.setMinimumSize(new java.awt.Dimension(640, 90));
        jPanelTituloVerCorredores.setPreferredSize(new java.awt.Dimension(640, 90));

        jLabelTituloVerCorredores.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTituloVerCorredores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloVerCorredores.setText("CORREDORES");
        jLabelTituloVerCorredores.setMinimumSize(new java.awt.Dimension(400, 70));
        jLabelTituloVerCorredores.setPreferredSize(new java.awt.Dimension(400, 70));

        javax.swing.GroupLayout jPanelTituloVerCorredoresLayout = new javax.swing.GroupLayout(jPanelTituloVerCorredores);
        jPanelTituloVerCorredores.setLayout(jPanelTituloVerCorredoresLayout);
        jPanelTituloVerCorredoresLayout.setHorizontalGroup(
            jPanelTituloVerCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloVerCorredoresLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabelTituloVerCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanelTituloVerCorredoresLayout.setVerticalGroup(
            jPanelTituloVerCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloVerCorredoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloVerCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTituloVerCorredores, java.awt.BorderLayout.PAGE_START);

        jScrollCorredores.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jListCorredores.setModel(jListCorredores.getModel());
        jListCorredores.setMaximumSize(null);
        jScrollCorredores.setViewportView(jListCorredores);

        javax.swing.GroupLayout jPanelListaCorredoresLayout = new javax.swing.GroupLayout(jPanelListaCorredores);
        jPanelListaCorredores.setLayout(jPanelListaCorredoresLayout);
        jPanelListaCorredoresLayout.setHorizontalGroup(
            jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelListaCorredoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollCorredores, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelListaCorredoresLayout.setVerticalGroup(
            jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
            .addGroup(jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelListaCorredoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollCorredores, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanelListaCorredores, java.awt.BorderLayout.CENTER);

        jPanelBotonesListaCorredores.setMinimumSize(new java.awt.Dimension(640, 100));

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesListaCorredoresLayout = new javax.swing.GroupLayout(jPanelBotonesListaCorredores);
        jPanelBotonesListaCorredores.setLayout(jPanelBotonesListaCorredoresLayout);
        jPanelBotonesListaCorredoresLayout.setHorizontalGroup(
            jPanelBotonesListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesListaCorredoresLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanelBotonesListaCorredoresLayout.setVerticalGroup(
            jPanelBotonesListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesListaCorredoresLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBotonesListaCorredores, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelTituloVerCorredores;
    private javax.swing.JList<String> jListCorredores;
    private javax.swing.JPanel jPanelBotonesListaCorredores;
    private javax.swing.JPanel jPanelListaCorredores;
    private javax.swing.JPanel jPanelTituloVerCorredores;
    private javax.swing.JScrollPane jScrollCorredores;
    // End of variables declaration//GEN-END:variables
}
