package gui;

import dto.Carrera;
import dto.Corredor;
import dto.TiemposCorredor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import logic.LogicaCorredor;
import utils.ExcepcionesPropias;

/**
 *
 * @author silvia
 */
public class VistaCorredores extends javax.swing.JDialog {

    PantallaPrincipal pantallaPrincipal;
    Carrera carreraParaAniadir;

    /**
     * Creates new form PantallaCorredor
     *
     * @param parent
     * @param modal
     */
    public VistaCorredores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        inicializarPantalla(parent);
        this.jButtonAniadirACarrera.setVisible(false);
    }

    public VistaCorredores(java.awt.Frame parent, boolean modal, Carrera carreraParaAniadir) {
        super(parent, modal);
        inicializarPantalla(parent);
        this.carreraParaAniadir = carreraParaAniadir;
        this.jButtonAniadirACarrera.setVisible(true);
    }

    private void inicializarPantalla(java.awt.Frame parent) {
        pantallaPrincipal = (PantallaPrincipal) parent;
        initComponents();
        setTitle("Corredores");
        setLocationRelativeTo(null);
        refrescarTablaCorredores();
        rellenarComboBoxOrdenCorredores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTituloVerCorredores = new javax.swing.JPanel();
        jLabelTituloVerCorredores = new javax.swing.JLabel();
        jPanelListaCorredores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jComboBoxOrdenCorredores = new javax.swing.JComboBox<>();
        jLabelOrdenCorredores = new javax.swing.JLabel();
        jPanelBotonesListaCorredores = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButtonNuevoCorredor = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonAniadirACarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanelTituloVerCorredores.setMinimumSize(new java.awt.Dimension(640, 90));
        jPanelTituloVerCorredores.setPreferredSize(new java.awt.Dimension(640, 90));

        jLabelTituloVerCorredores.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTituloVerCorredores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloVerCorredores.setText("CORREDORES");
        jLabelTituloVerCorredores.setMinimumSize(new java.awt.Dimension(400, 70));
        jLabelTituloVerCorredores.setPreferredSize(new java.awt.Dimension(400, 70));

        javax.swing.GroupLayout jPanelTituloVerCorredoresLayout = new javax.swing.GroupLayout(jPanelTituloVerCorredores);
        jPanelTituloVerCorredores.setLayout(jPanelTituloVerCorredoresLayout);
        jPanelTituloVerCorredoresLayout.setHorizontalGroup(
            jPanelTituloVerCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloVerCorredoresLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabelTituloVerCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelTituloVerCorredoresLayout.setVerticalGroup(
            jPanelTituloVerCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloVerCorredoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloVerCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTituloVerCorredores, java.awt.BorderLayout.PAGE_START);

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCorredores);

        jComboBoxOrdenCorredores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOrdenCorredores.setToolTipText("");
        jComboBoxOrdenCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrdenCorredoresActionPerformed(evt);
            }
        });

        jLabelOrdenCorredores.setText("Orden");

        javax.swing.GroupLayout jPanelListaCorredoresLayout = new javax.swing.GroupLayout(jPanelListaCorredores);
        jPanelListaCorredores.setLayout(jPanelListaCorredoresLayout);
        jPanelListaCorredoresLayout.setHorizontalGroup(
            jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaCorredoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelOrdenCorredores)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxOrdenCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanelListaCorredoresLayout.setVerticalGroup(
            jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaCorredoresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrdenCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrdenCorredores))
                .addContainerGap())
        );

        getContentPane().add(jPanelListaCorredores, java.awt.BorderLayout.CENTER);

        jPanelBotonesListaCorredores.setMinimumSize(new java.awt.Dimension(640, 100));

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonNuevoCorredor.setText("Nuevo");
        jButtonNuevoCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoCorredorActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonAniadirACarrera.setText("Añadir a carrera");
        jButtonAniadirACarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirACarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesListaCorredoresLayout = new javax.swing.GroupLayout(jPanelBotonesListaCorredores);
        jPanelBotonesListaCorredores.setLayout(jPanelBotonesListaCorredoresLayout);
        jPanelBotonesListaCorredoresLayout.setHorizontalGroup(
            jPanelBotonesListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesListaCorredoresLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jButtonNuevoCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBotonesListaCorredoresLayout.createSequentialGroup()
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrar))
                    .addComponent(jButtonAniadirACarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jPanelBotonesListaCorredoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBorrar, jButtonModificar, jButtonNuevoCorredor});

        jPanelBotonesListaCorredoresLayout.setVerticalGroup(
            jPanelBotonesListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesListaCorredoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAniadirACarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesListaCorredoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevoCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonBorrar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelBotonesListaCorredoresLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAniadirACarrera, jButtonBorrar, jButtonModificar, jButtonNuevoCorredor});

        getContentPane().add(jPanelBotonesListaCorredores, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // SALIR
    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // TABLA
    private void refrescarTablaCorredores() {
        this.jTableCorredores.setModel(new TableModelCorredor());
    }

    private void rellenarComboBoxOrdenCorredores() {
        this.jComboBoxOrdenCorredores.setModel(new DefaultComboBoxModel<>(LogicaCorredor.getInstance().getOpcionesOrdenCorredores()));
    }

    private void jComboBoxOrdenCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrdenCorredoresActionPerformed
        switch (jComboBoxOrdenCorredores.getSelectedIndex()) {
            case 0:
                LogicaCorredor.getInstance().ordenarDni();
                break;
            case 1:
                LogicaCorredor.getInstance().ordenarNombre();
                break;
            case 2:
                LogicaCorredor.getInstance().ordenarFechaNac();
                break;
        }
        refrescarTablaCorredores();
    }//GEN-LAST:event_jComboBoxOrdenCorredoresActionPerformed

    // BOTONES
    private void jButtonNuevoCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoCorredorActionPerformed
        FormularioCorredores ventanaCorredor = new FormularioCorredores(pantallaPrincipal, true);
        ventanaCorredor.setVisible(true);
        refrescarTablaCorredores();
    }//GEN-LAST:event_jButtonNuevoCorredorActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int seleccionado = jTableCorredores.getSelectedRow();
        if (seleccionado != -1) {
            Corredor corredor = LogicaCorredor.getInstance().getCorredores().get(seleccionado);
            FormularioCorredores ventanaCorredor = new FormularioCorredores(pantallaPrincipal, true, corredor);
            ventanaCorredor.setVisible(true);
            refrescarTablaCorredores();
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un corredor", "Selecciona corredor", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int seleccionado = jTableCorredores.getSelectedRow();
        if (seleccionado != -1) {
            try {
                LogicaCorredor.getInstance().bajaCorredor(LogicaCorredor.getInstance().getCorredores().get(seleccionado));
                refrescarTablaCorredores();
            } catch (ExcepcionesPropias.CorredorNoEsta ex) {
                JOptionPane.showMessageDialog(this, "El corredor no existe", "Corredor no existe", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un corredor", "Selecciona corredor", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonAniadirACarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirACarreraActionPerformed
        if (carreraParaAniadir != null) {
            List<TiemposCorredor> corredores = new ArrayList<>();
            for (int i : this.jTableCorredores.getSelectedRows()) {
                corredores.add(new TiemposCorredor(this.carreraParaAniadir.getId(), LogicaCorredor.getInstance().getCorredores().get(i)));
            }
            try {
                carreraParaAniadir.addCorredores(corredores);
                this.dispose();
            } catch (ExcepcionesPropias.CarreraCerrada ex) {
                JOptionPane.showMessageDialog(this, "La carrera está cerrada y no se pueden añadir corredores", "Carrera cerrada", JOptionPane.INFORMATION_MESSAGE);
            } catch (ExcepcionesPropias.DemasiadosCorredores ex) {
                JOptionPane.showMessageDialog(this, "No se puede superar el número máximo de corredores para la carrera", "Demasiados corredores", JOptionPane.INFORMATION_MESSAGE);
            } catch (ExcepcionesPropias.CorredorRepetido ex) {
                JOptionPane.showMessageDialog(this, "El corredor ya esta incluido en la lista de corredores de la carrera", "Corredor repetido", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAniadirACarreraActionPerformed

    //  MODELO DE TABLA
    public static class TableModelCorredor extends AbstractTableModel {

        @Override
        public String getColumnName(int column) {
            return Corredor.DATOS[column];
        }

        @Override
        public int getRowCount() {
            return LogicaCorredor.getInstance().getCorredores().size();
        }

        @Override
        public int getColumnCount() {
            return Corredor.DATOS.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            String array[] = LogicaCorredor.getInstance().getCorredores().get(rowIndex).toArray();
            return array[columnIndex];
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAniadirACarrera;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevoCorredor;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxOrdenCorredores;
    private javax.swing.JLabel jLabelOrdenCorredores;
    private javax.swing.JLabel jLabelTituloVerCorredores;
    private javax.swing.JPanel jPanelBotonesListaCorredores;
    private javax.swing.JPanel jPanelListaCorredores;
    private javax.swing.JPanel jPanelTituloVerCorredores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables
}
